language: bash

install:
  - bin/fetch-configlet
  - git clone https://github.com/vlang/v
  - cd v
  - make
  - cd ..

script:
  - bin/configlet lint --track-id v .
  - v=v/v sh test-good-exercises.sh
  - v=v/v sh test-broken-exercises.sh
